### ISSUE TITLE
doesnt compile, please provide build instructions

### ISSUE THREAD

**Issue by mathew2214** [Rosalie241/SporeServer#3]
when trying to compile this the normal .net way, i get the error

```
mathew2214@Aisling:~/sporeserver/SporeServer$ dotnet msbuild SporeServer.sln 
MSBuild version 17.9.6+a4ecab324 for .NET
/home/mathew2214/sporeserver/SporeServer/SporeMods/SporeServer/SporeServer.vcxproj(32,3): error MSB4019: The imported project "/Microsoft.Cpp.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.props" is correct, and that the file exists on disk.
  SporeServer.Utils -> /home/mathew2214/sporeserver/SporeServer/SporeServer.Utils/bin/Debug/net7.0/SporeServer.Utils.dll
  SporeServer -> /home/mathew2214/sporeserver/SporeServer/SporeServer/bin/Debug/net7.0/SporeServer.dll
  SporeServer.Tests -> /home/mathew2214/sporeserver/SporeServer/SporeServer.Tests/bin/Debug/net7.0/SporeServer.Tests.dll


```

please either provide a list of dependencies, build instructions, or remove this "Microsoft.Cpp.props" reference to remove the need for this undocumented dependency.

**Comment by Rosalie241** [comment]
1) using `dotnet msbuild` isn't the normal way to run or build msbuild projects.
2) the default sln file includes the spore mod which is required to connect to the server aswell, which requires visual studio, just cd into the `SporeServer` directory and use `dotnet run` on Linux, you'll also need to use `dotnet ef` to initialize and migrate the database.
3) I'll provide instructions when the spore server is more ready, it currently isn't meant to be run by end-users or hosted anywhere, the current status of the project is work-in-progress so please don't open further issues about things missing or not working, I know about them and will fix them when I have the energy and time for it.
